language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    -

script: "./gradlew clean build"

before_deploy:
  - zip -r inven *
  - mkdir -p deploy
  - mv inven.zip deploy/inven.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: inven-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: inven-springboot-build
    key: inven.zip
    bundle_type: zip
    application: inven
    default_text_charset: inven_group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - denhenker@naver.com
