spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://freelec-springboot2-webservice.cih7uhogpjdw.ap-northeast-2.rds.amazonaws.com:3306/inven?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Gkstmvns1!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
