# Mysql8 설정
spring:
  datasource:
    url: jdbc:mysql://freelec-springboot2-webservice.cih7uhogpjdw.ap-northeast-2.rds.amazonaws.com:3306/inven?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Gkstmvns1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    open-in-view: false



